[package]
name = "wgpu-forray"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = "1.21.0"
glfw = "0.59.0"
image = "0.25.5"
pollster = "0.4.0"
tokio = { version = "1.43.0", features = ["full"] }
wgpu = "24.0.1"
wgpu-hal = "24.0.0"
